"""
Migrate an existing run to the zone-free schema. No refetching.

WHY THIS IS SAFE
----------------
The README's rule is that changing anything under `study_area:` or
`sampling:` invalidates the frame, because Stage 1 reassigns node_id from
n00000 and the same ID then points at a different corner. Removing `zones:`
is not that. Zone was an attribute computed from lat/lon AFTER the node IDs
were assigned; it never touched node placement, dedupe or ordering. The
README says as much: changing only `directional:`, `zones:` or `spatial:`
is analysis-only.

So the earlier advice to wipe data/raw/svi and re-fetch was wrong, and this
script is the correct path: it edits the frame attributes in place and
leaves every node_id, every pano_id and every JPEG exactly where it was.

WHY NOT JUST RE-RUN s01
-----------------------
Re-running Stage 1 would also be free, but it re-queries OSM. If the
OSMnx cache has expired and the underlying OSM data has changed at all
since the original run, the node count changes, IDs shift, and s02 aborts
on the stale-imagery check -- which would then genuinely force a refetch.
Editing in place cannot drift.

    python migrate_gridaxis.py            # dry run, reports what it would do
    python migrate_gridaxis.py --apply

Then:

    python main.py --from s04             # seconds, no GPU, no API key
"""
import argparse, sys
from pathlib import Path

import pandas as pd

HERE = Path(__file__).parent
sys.path.insert(0, str(HERE))
from gridaxis import grid_northing, grid_easting

PROC = HERE / "data" / "processed"
RAW = HERE / "data" / "raw"

ap = argparse.ArgumentParser()
ap.add_argument("--apply", action="store_true",
                help="write the changes (default is a dry run)")
a = ap.parse_args()
DRY = not a.apply


def report(path, adds, drops):
    tag = "would " if DRY else ""
    print(f"  {path.name}")
    if adds:
        print(f"    {tag}add   {', '.join(adds)}")
    if drops:
        print(f"    {tag}drop  {', '.join(drops)}")
    if not adds and not drops:
        print("    nothing to do")


def do_frame():
    """nodes.gpkg is the one that matters -- s04 reads its attributes."""
    import geopandas as gpd
    p = PROC / "nodes.gpkg"
    if not p.exists():
        print(f"  {p} not found -- skipping")
        return
    g = gpd.read_file(p)
    if not {"lat", "lon"}.issubset(g.columns):
        w = g.to_crs(4326)
        g["lat"], g["lon"] = w.geometry.y, w.geometry.x
    adds = [c for c in ("northing_m", "easting_m") if c not in g.columns]
    drops = [c for c in ("zone",) if c in g.columns]
    report(p, adds, drops)
    if DRY:
        return
    g["northing_m"] = grid_northing(g.lat, g.lon)
    g["easting_m"] = grid_easting(g.lat, g.lon)
    g = g.drop(columns=drops)
    g.to_file(p, driver="GPKG")


def do_csv(path, latc="lat", lonc="lon", add_axes=True):
    if not path.exists():
        print(f"  {path.name} not found -- skipping")
        return
    d = pd.read_csv(path)
    have = {latc, lonc}.issubset(d.columns)
    adds = ([c for c in ("northing_m", "easting_m") if c not in d.columns]
            if (add_axes and have) else [])
    drops = [c for c in ("zone",) if c in d.columns]
    report(path, adds, drops)
    if DRY or (not adds and not drops):
        return
    if adds:
        d["northing_m"] = grid_northing(d[latc], d[lonc])
        d["easting_m"] = grid_easting(d[latc], d[lonc])
    d = d.drop(columns=drops)
    d.to_csv(path, index=False)


print(__doc__.split("    python")[0])
print("dry run -- nothing written. Re-run with --apply.\n" if DRY
      else "applying changes\n")

print("frame:")
do_frame()

print("\nmetadata cache (a stale `zone` column here survives s02's drop list):")
do_csv(RAW / "metadata.csv", "node_lat", "node_lon", add_axes=False)

print("\nderived tables (these are regenerated by s04 anyway; cleaned so a")
print("part-way state is not left carrying a column that no longer exists):")
for f, la, lo in [("metrics.csv", "lat", "lon"),
                  ("directional_metrics.csv", "lat", "lon"),
                  ("directional_metrics_wide.csv", "lat", "lon"),
                  ("nodes_with_faces.csv", "lat", "lon"),
                  ("block_faces.csv", None, None)]:
    if la is None:
        do_csv(PROC / f, add_axes=False)
    else:
        do_csv(PROC / f, la, lo)

print("\nimagery and profiles are untouched:")
for p, what in [(RAW / "svi", "JPEGs"),
                (PROC / "azimuth_profiles.npz", "segmented profiles"),
                (PROC / "manifest.csv", "image manifest")]:
    n = len(list(p.glob("*.jpg"))) if p.is_dir() else int(p.exists())
    print(f"  {what:22s} {'present' if n else 'absent'}"
          f"{f' ({n} files)' if p.is_dir() else ''}")

print("\nnext:  python main.py --from s04")
print("  Stage 4 rebuilds metrics, faces and Moran from the saved profiles.")
print("  No GPU, no GMAPS_KEY, no network. Seconds.")
if DRY:
    print("\n(dry run -- re-run with --apply to write)")
