"""Turn the Vision-Model-Segmentation-Taxonomy notebook into a batch script.

The notebook is a linear Colab document: 32 cells sharing module-level state,
`/content` paths, `files.upload()` for exactly one image, and 14 `display()`
calls. None of that survives a 3,064-image run, but the pipeline between the
input and the writes is what we want, so this converts rather than reimplements
-- a reimplementation would drift from the colleague's version the moment
either side changed.

What is replaced, and nothing else:

  cells 0-1   pip installs                 dropped; deps live in .venv-gpu
  cell 2      PROJECT_ROOT = /content/...  pointed at --out
  cell 4      files.upload()               reads the path in VMST_IMAGE
  display()   Colab rendering              no-op
  plt.show()  blocking                     no-op, figures still saved

    .venv-gpu/Scripts/python tools/vmst_build.py --nb <notebook> --out vmst_run.py
"""
import argparse
import json
import re
from pathlib import Path

HEADER = '''"""GENERATED by tools/vmst_build.py -- do not edit by hand.

Source: {src}
Regenerate after any change to the notebook.
"""
import os, sys
import matplotlib
matplotlib.use("Agg")

VMST_IMAGE = os.environ["VMST_IMAGE"]
VMST_OUT = os.environ["VMST_OUT"]


class _NoDisplay:
    def __call__(self, *a, **k):
        return None


display = _NoDisplay()

# transformers >= 4.56 refuses torch.load unless torch >= 2.6 (CVE-2025-32434)
# and still resolves a repo's .bin ahead of a locally converted
# model.safetensors. This machine pins torch 2.5.1+cu124 against its CUDA
# build, so the loader flag moves rather than the stack.
# tools/hf_bin_to_safetensors.py writes the safetensors beside the .bin.
from transformers.modeling_utils import PreTrainedModel as _PTM

_orig_from_pretrained = _PTM.from_pretrained.__func__


@classmethod
def _from_pretrained_safe(cls, *a, **kw):
    kw.setdefault("use_safetensors", True)
    return _orig_from_pretrained(cls, *a, **kw)


_PTM.from_pretrained = _from_pretrained_safe
'''

INPUT_CELL = '''
# --- replaced: the Colab upload step -------------------------------------
import io, re
from pathlib import Path
from PIL import Image

image = Image.open(VMST_IMAGE).convert("RGB")
W, H = image.size
filename = Path(VMST_IMAGE).name
TEST_ID = re.sub(r"[^A-Za-z0-9_-]+", "_", Path(filename).stem).upper()
print("Current test:", TEST_ID, "|", filename, "|", image.size, flush=True)
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--nb", type=Path, required=True)
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args()

    nb = json.loads(args.nb.read_text(encoding="utf-8"))
    cells = [c for c in nb["cells"] if c["cell_type"] == "code"]
    parts = [HEADER.format(src=args.nb.name)]

    for i, c in enumerate(cells):
        s = "".join(c["source"])
        if s.lstrip().startswith("!pip") or "pip uninstall" in s:
            continue
        if "files.upload()" in s:
            parts.append(INPUT_CELL)
            continue
        # Colab-only imports and blocking calls
        s = re.sub(r"^\s*from google\.colab import .*$", "", s, flags=re.M)
        s = re.sub(r"^\s*from IPython\.display import .*$", "", s, flags=re.M)
        s = re.sub(r"^(\s*)plt\.show\(\)", r"\1plt.close('all')", s, flags=re.M)
        # the one hard-coded root
        s = s.replace('Path("/content/VLM_Street_Interface_Segmentation")',
                      'Path(VMST_OUT)')
        s = s.replace('"/content/VLM_Street_Interface_Segmentation"', 'VMST_OUT')
        s = s.replace("/content/", "")
        parts.append(f"\n# ===== cell {i} " + "=" * 52 + "\n" + s)

    args.out.write_text("\n".join(parts), encoding="utf-8")
    n = sum(1 for p in parts if p.startswith("\n# ===== cell"))
    print(f"wrote {args.out}  ({n} cells kept of {len(cells)})")


if __name__ == "__main__":
    main()
